### PR TITLE
Do 1178 cli system api commands for babylon

### PR DESCRIPTION
**Pull request by shambupujar**

### CODE REVIEW

**Comment by kofrdx** [comment]
I checked the behaviour of the commands against Gilganet Node.

It works well. All give back valid responses. However I feel the output of some can be modified to improve user expierience. Currently we are giving back unmodified json responses. In a real release, this might not look pretty enough. Its worth considering a story for "pretty-print"-option.

This comes into play when using `radixnode api system metrics`. The output is basically unreadable. Even parsed into a file, it would need refactoring of replacing \n with an actual new line. The `radixnode api metrics` command already prints a pretty version of this. Since its duplicated, we might consider removing one or merging them into different output formats as an argument like "--output-format json/pretty".

Otherwise I really like the approach of encapsulating the code and keeping it very slim for an eventual replacement client.

**Review by kofrdx — APPROVED** [review]
Looks good. 
Might be worth thinking about removing either
 - radixnode api system metrics or
 - radixnode api metrics
 
 The output of `radixnode api metrics` is more readable though. But the `api system metrics` is closer to an actual delivered api client generated from OpenAPI Docs.

**Comment by shambupujar** [comment]
> 
`radixnode api system metrics ` has been removed and only `radixnode api metrics` is made avaliable

**Comment by shambupujar** [comment]
> 
> It works well. All give back valid responses. However I feel the output of some can be modified to improve user expierience. Currently we are giving back unmodified json responses. In a real release, this might not look pretty enough. Its worth considering a story for "pretty-print"-option.
> 
The output is kept simple so that one can parse it using jq. We potentially can add a environment variable that if set , it prints pretty

**Pull request merged**
